name: Merge queue test

on:
  merge_group:
  pull_request:

jobs:
  test-mq:
    name: Test merge queue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      # Foo
      - name: Print rustup components
        run: |
          rustup toolchain list -v
          rustc --version

  create_pr:
    permissions:
      # The cronjob needs to be able to push to the repo...
      contents: write
      # ... and create a PR.
      pull-requests: write
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup bot git name and email
        run: |
          git config --global user.name 'The Miri Cronjob Bot'
          git config --global user.email 'miri@cron.bot'
      - name: Push changes to a branch
        if: ${{ github.event_name == 'merge_group' }}
        run: |
          BRANCH="rustup-$(date -u +%Y-%m-%d-%H-%M-%S)"
          git checkout -b $BRANCH
          ls -lha .
          pwd
          touch a.txt
          echo "hello" >> a.txt
          git add a.txt
          git commit -m"WIP"
          git push -u origin $BRANCH
      - name: Create PR
        if: ${{ github.event_name == 'merge_group' }}
        run: gh pr create -B main --title 'Automatic Rustup' --body 'bar'
        env:
          GH_TOKEN: ${{ secrets.PR_CREATION_TOKEN }}
